language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - pypy
script:
    - wget http://dl.4players.de/ts/releases/3.0.10.2/teamspeak3-server_linux-amd64-3.0.10.2.tar.gz
    - tar xzf teamspeak3-server_linux-amd64-3.0.10.2.tar.gz
    - cd teamspeak3-server_linux-amd64
    - ./ts3server_linux_amd64
    - ./ts3server_startscript.sh start serveradmin_password=travis_test
    - cd ../
    - sleep 5
    - python run_tests.py
