language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - pypy
script:
    - mount -t tmpfs tmpfs /dev/shm # http://forum.teamspeak.com/showthread.php/68827-Failed-to-register-local-accounting-service
    - wget http://dl.4players.de/ts/releases/3.0.10.2/teamspeak3-server_linux-amd64-3.0.10.2.tar.gz
    - tar xzf teamspeak3-server_linux-amd64-3.0.10.2.tar.gz
    - cd teamspeak3-server_linux-amd64
    - ./ts3server_linux_amd64
    - ./ts3server_startscript.sh start serveradmin_password=travis_test
    - cd ../
    - python run_tests.py
